security:
    encoders:
        Wikimap\MainBundle\Entity\User: sha512
        
    role_hierarchy:
        ROLE_USER:    [ROLE_DEFAULT]
        ROLE_MODERATEUR:    [ROLE_USER]
        ROLE_ADMIN: [ROLE_MODERATEUR, ROLE_ALLOWED_TO_SWITCH]
        
    providers:
        main:
            id: fos_user.user_provider.username_email

    firewalls:
        main:
            pattern: ^/
            anonymous: true
            provider: main
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                remember_me: true
            logout:
                path:    fos_user_security_logout
                target:    /
            remember_me:
                secret: %secret%
                lifetime: 31536000
                always_remember_me: true
            switch_user: { role: ROLE_ADMIN }
        
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
            
    access_control:
            - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/admin/, role: ROLE_ADMIN }

